spring.application.name=gestao

# Configurações de Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://187.77.46.129:5433/igreja
spring.datasource.username=postgres
spring.datasource.password=ipdosipes
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração de schema padrão (opcional dependendo de como está montado seu DB)
spring.jpa.properties.hibernate.default_schema=gestao

# Permite o Spring ler requests Multipart com tamanho maior caso venham muitos CSVs
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
